/**
 * CI/CD workflow generation for a built add-on (roadmap item: the builder emits a
 * ready-to-run GitHub Actions pipeline when you connect the add-on to GitHub).
 *
 * The generated workflow is self-contained (ucc-gen build + AppInspect via Splunk's own
 * published action) so it runs without any external setup. A comment points at the shared
 * `livehybrid/deploy-splunk-app-action` reusable pipeline as the upgrade path for
 * publishing/Splunkbase.
 */

export const CI_WORKFLOW_PATH = '.github/workflows/build-validate.yml';

export function buildValidateWorkflowYaml(appId: string): string {
  const app = (appId || 'TA_my_addon').replace(/[^A-Za-z0-9_-]/g, '_');
  return `# Generated by UCC App Builder — build + AppInspect for ${app}.
# Upgrade path: replace the steps below with the shared reusable pipeline
#   uses: livehybrid/deploy-splunk-app-action/.github/workflows/build.yml@main
# (which also offers appinspect-api cloud vetting + Splunkbase publish).
name: Build & Validate Splunk Add-on

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

jobs:
  build-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install UCC framework + AppInspect
        run: pip install "splunk-add-on-ucc-framework>=6.5.0" "splunk-appinspect>=4.2.1"

      - name: Build with ucc-gen
        # The add-on source (globalConfig.json + package/) is at the repo root.
        run: ucc-gen build --source . -o "$RUNNER_TEMP/build"

      - name: Package tarball
        run: tar czf "$RUNNER_TEMP/${app}.tar.gz" -C "$RUNNER_TEMP/build" "${app}"

      - name: AppInspect (Splunk's official action, cloud tags)
        uses: splunk/appinspect-cli-action@v2.13.0
        with:
          app_path: \${{ runner.temp }}/${app}.tar.gz
          included_tags: cloud

      - name: Upload package
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${app}
          path: \${{ runner.temp }}/${app}.tar.gz
          if-no-files-found: ignore
`;
}
