/**
 * REST API Polling Template
 *
 * A production-ready template for polling REST API endpoints at regular intervals.
 * Includes error handling, rate limiting awareness, and proper logging.
 */

import type { Template } from '../types/templates';

/**
 * Python script for REST API polling input
 * Placeholders: {{INPUT_NAME}}, {{INPUT_TITLE}}, {{CLASS_NAME}}
 */
export const REST_API_POLLING_SCRIPT = `"""
REST API Polling Input
Collects data from a REST API endpoint at configurable intervals.

Generated by UCC App Builder
"""
import sys
import os
import json
import time

# Add lib directory to path for dependencies
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'lib'))

import requests
from splunklib.modularinput import Script, Scheme, Argument, Event


class RestApiPollingInput(Script):
    """
    Modular input that polls a REST API endpoint and indexes the response.
    """

    def get_scheme(self):
        """Define the input's parameters."""
        scheme = Scheme("REST API Polling")
        scheme.description = "Polls a REST API endpoint at regular intervals"
        scheme.use_external_validation = True
        scheme.use_single_instance = False

        scheme.add_argument(Argument(
            name="api_url",
            title="API URL",
            description="The REST API endpoint URL to poll",
            required_on_create=True,
            data_type=Argument.data_type_string
        ))

        scheme.add_argument(Argument(
            name="api_key",
            title="API Key",
            description="API key for authentication (optional)",
            required_on_create=False,
            data_type=Argument.data_type_string
        ))

        scheme.add_argument(Argument(
            name="request_timeout",
            title="Request Timeout",
            description="HTTP request timeout in seconds",
            required_on_create=False,
            data_type=Argument.data_type_number
        ))

        return scheme

    def validate_input(self, definition):
        """Validate the input configuration before saving."""
        api_url = definition.parameters.get("api_url", "")
        
        if not api_url:
            raise ValueError("API URL is required")
        
        if not api_url.startswith(("http://", "https://")):
            raise ValueError("API URL must start with http:// or https://")
        
        timeout = definition.parameters.get("request_timeout", "30")
        try:
            timeout_int = int(timeout)
            if timeout_int < 1 or timeout_int > 300:
                raise ValueError("Request timeout must be between 1 and 300 seconds")
        except (ValueError, TypeError):
            raise ValueError("Request timeout must be a valid number")

    def stream_events(self, inputs, ew):
        """Collect data from the API and stream events to Splunk."""
        for input_name, input_item in inputs.inputs.items():
            try:
                self._collect_events(input_name, input_item, ew)
            except Exception as e:
                ew.log("ERROR", f"Error collecting from {input_name}: {str(e)}")

    def _collect_events(self, input_name, input_item, ew):
        """Collect events from a single input configuration."""
        api_url = input_item.get("api_url", "")
        api_key = input_item.get("api_key", "")
        timeout = int(input_item.get("request_timeout", "30"))

        # Build request headers
        headers = {
            "Content-Type": "application/json",
            "Accept": "application/json",
            "User-Agent": "Splunk-UCC-Input/1.0"
        }
        
        if api_key:
            headers["Authorization"] = f"Bearer {api_key}"

        ew.log("INFO", f"Polling API: {api_url}")

        try:
            response = requests.get(
                api_url,
                headers=headers,
                timeout=timeout
            )
            response.raise_for_status()
            
            data = response.json()
            
            # Handle both array and object responses
            if isinstance(data, list):
                records = data
            elif isinstance(data, dict):
                # Check for common wrapper patterns
                records = data.get("results", data.get("data", data.get("items", [data])))
            else:
                records = [data]

            event_count = 0
            for record in records:
                event = Event()
                event.stanza = input_name
                event.data = json.dumps(record)
                event.time = time.time()
                ew.write_event(event)
                event_count += 1

            ew.log("INFO", f"Successfully collected {event_count} events from {api_url}")

        except requests.exceptions.Timeout:
            ew.log("WARN", f"Request timed out after {timeout}s for {api_url}")
        except requests.exceptions.HTTPError as e:
            ew.log("ERROR", f"HTTP error {e.response.status_code}: {e.response.text[:200]}")
        except requests.exceptions.ConnectionError as e:
            ew.log("ERROR", f"Connection error for {api_url}: {str(e)}")
        except json.JSONDecodeError as e:
            ew.log("ERROR", f"Invalid JSON response from {api_url}: {str(e)}")


if __name__ == "__main__":
    sys.exit(RestApiPollingInput().run(sys.argv))
`;

/**
 * REST API Polling Template Definition
 */
export const restApiPollingTemplate: Template = {
  metadata: {
    id: 'rest-api-polling',
    name: 'REST API Polling',
    description:
      'Poll any REST API endpoint at configurable intervals with authentication support.',
    category: 'rest-api',
    tags: ['rest', 'api', 'polling', 'http', 'json'],
    difficulty: 'beginner',
    version: '1.0.0',
    icon: '🌐',
  },

  inputs: [
    {
      config: {
        name: 'rest_api_input',
        title: 'REST API Input',
        description: 'Collects data from a REST API endpoint',
        entity: [
          {
            field: 'name',
            label: 'Input Name',
            type: 'text',
            required: true,
            help: 'A unique name for this input instance',
            validators: [
              { type: 'string', minLength: 1, maxLength: 100 },
              {
                type: 'regex',
                pattern: '^[a-zA-Z][a-zA-Z0-9_]*$',
                errorMsg:
                  'Must start with a letter and contain only letters, numbers, and underscores',
              },
            ],
          },
          {
            field: 'api_url',
            label: 'API URL',
            type: 'text',
            required: true,
            help: 'The REST API endpoint URL to poll (e.g., https://api.example.com/data)',
            validators: [{ type: 'url', errorMsg: 'Please enter a valid URL' }],
          },
          {
            field: 'interval',
            label: 'Polling Interval',
            type: 'text',
            required: true,
            defaultValue: '300',
            help: 'How often to poll the API (in seconds)',
            validators: [
              {
                type: 'number',
                min: 60,
                max: 86400,
                errorMsg: 'Interval must be between 60 and 86400 seconds',
              },
            ],
          },
          {
            field: 'api_key',
            label: 'API Key',
            type: 'password',
            required: false,
            encrypted: true,
            help: 'API key for Bearer token authentication (optional)',
          },
          {
            field: 'request_timeout',
            label: 'Request Timeout',
            type: 'text',
            required: false,
            defaultValue: '30',
            help: 'HTTP request timeout in seconds',
            validators: [
              {
                type: 'number',
                min: 1,
                max: 300,
                errorMsg: 'Timeout must be between 1 and 300 seconds',
              },
            ],
          },
          {
            field: 'index',
            label: 'Index',
            type: 'text',
            required: true,
            defaultValue: 'main',
            help: 'Splunk index to store the data',
          },
        ],
      },
      pythonScript: REST_API_POLLING_SCRIPT,
    },
  ],

  recommendedTabs: {
    enableLogging: true,
    enableProxy: true,
  },

  documentation: `## REST API Polling Template

This template creates a modular input that polls a REST API endpoint at regular intervals and indexes the JSON response.

### Features
- **Configurable polling interval** - Set how often to fetch data
- **Bearer token authentication** - Securely store and use API keys
- **Automatic response parsing** - Handles both array and object responses
- **Error handling** - Logs errors without crashing the input
- **Timeout configuration** - Prevent hanging requests

### Common Use Cases
- Collecting metrics from monitoring APIs
- Fetching data from SaaS applications
- Polling status endpoints
- Ingesting data from internal services

### After Applying
1. Review the generated Python script in \`bin/rest_api_input.py\`
2. Customize the response parsing if needed
3. Add any additional fields your API requires
`,

  prerequisites: ['API endpoint URL', 'API key or authentication credentials (if required)'],

  addsSummary: [
    '1 Input: "REST API Input" with URL, interval, and API key fields',
    'Python script with error handling and logging',
    'Enables Logging and Proxy configuration tabs',
  ],
};
