import { Tool } from '../toolTypes';

export interface InputScriptParam {
  name: string;
  required?: boolean;
  description?: string;
}

export interface BuildInputScriptOptions {
  input_name: string;
  description: string;
  parameters?: InputScriptParam[];
  use_checkpoint?: boolean;
}

/**
 * Pure, side-effect-free generator for a UCC modular-input handler script.
 *
 * Extracted from the `generate_input_script` tool so the SAME template can be
 * reused as a DETERMINISTIC auto-stub when a build is found to declare an input
 * service in globalConfig.json but ship no `package/bin/<name>.py` handler.
 * Keeping one source of truth means the auto-stub stays AppInspect-/syntax-clean
 * exactly like the tool output.
 */
export function buildInputScript(opts: BuildInputScriptOptions): string {
  const input_name = opts.input_name;
  const description = opts.description;
  const parameters = opts.parameters ?? [];
  const use_checkpoint = opts.use_checkpoint ?? false;

  // Generate script based on type
  const className =
    input_name
      .split('_')
      .map((w: string) => w.charAt(0).toUpperCase() + w.slice(1))
      .join('') + 'Input';

  let script = `"""
${description}
Generated by UCC App Builder AI Assistant
"""
import import_declare_test  # noqa: F401  (UCC: must be first; fixes sys.path for bundled libs)

import sys
import json
import logging

from splunklib import modularinput as smi

class ${className}(smi.Script):
    def __init__(self):
        super(${className}, self).__init__()

    def get_scheme(self):
        scheme = smi.Scheme("${input_name}")
        scheme.description = "${description}"
        scheme.use_external_validation = True
        scheme.streaming_mode_xml = True
        scheme.use_single_instance = False

        # Add arguments
`;

  // Add parameters
  parameters.forEach((param) => {
    script += `
        arg = smi.Argument("${param.name}")
        arg.title = "${param.name.replace(/_/g, ' ').replace(/\b\w/g, (c: string) => c.toUpperCase())}"
        arg.description = "${param.description || ''}"
        arg.required_on_create = ${param.required ? 'True' : 'False'}
        scheme.add_argument(arg)
`;
  });

  script += `
        return scheme

    def validate_input(self, validation_definition):
        # Validation logic here
        pass

    def stream_events(self, inputs, ew):
        # Collection logic here
        # inputs object contains the configuration for each input instance
        for input_name, input_item in inputs.inputs.items():
            # Extract parameters
`;

  parameters.forEach((param) => {
    script += `            ${param.name} = input_item.get("${param.name}")\n`;
  });

  if (use_checkpoint) {
    script += `
            # Checkpointing logic
            checkpoint_dir = inputs.metadata.get("checkpoint_dir")
            # Implement checkpoint read/write here
`;
  }

  script += `
            # Main collection loop
            try:
                # TODO: Implement data collection
                pass

                # Example even creation:
                # event = smi.Event()
                # event.stanza = input_name
                # event.data = "sample data"
                # ew.write_event(event)

            except Exception as e:
                ew.log(smi.EventWriter.ERROR, f"Error collecting data: {str(e)}")

if __name__ == "__main__":
    exit_code = ${className}().run(sys.argv)
    sys.exit(exit_code)
`;

  return script;
}

export const generateInputScript: Tool = {
  name: 'generate_input_script',
  description:
    'Generate a Python modular input script based on requirements. Returns the complete script content.',
  parameters: {
    type: 'object',
    properties: {
      input_name: { type: 'string', description: 'Name of the input (e.g., my_api_input)' },
      input_type: {
        type: 'string',
        description: 'Type of input: rest_api, database, file_monitor, webhook, or custom',
        enum: ['rest_api', 'database', 'file_monitor', 'webhook', 'custom'],
      },
      description: { type: 'string', description: 'Description of what the input collects' },
      parameters: {
        type: 'array',
        description: 'Array of parameter objects with name, required, and description',
        items: {
          type: 'object',
          properties: {
            name: { type: 'string' },
            required: { type: 'boolean' },
            description: { type: 'string' },
          },
        },
      },
      use_checkpoint: {
        type: 'boolean',
        description: 'Whether to include checkpointing for incremental collection',
      },
    },
    required: ['input_name', 'input_type', 'description'],
  },
  execute: async (args, _vfs) => {
    return buildInputScript({
      input_name: args.input_name as string,
      description: args.description as string,
      parameters: (args.parameters || []) as InputScriptParam[],
      use_checkpoint: (args.use_checkpoint || false) as boolean,
    });
  },
};
