/**
 * UCC Build Manifest types
 * Tracks file origins for CI/CD-friendly development
 */

/**
 * Classification of a file's origin
 */
export type FileOrigin =
  | 'source'              // User-created, version controlled (globalConfig.json, custom scripts)
  | 'generated'           // Created by ucc-gen, can be regenerated
  | 'modified-generated'  // Generated but manually modified by user
  | 'custom';             // User-added files not part of UCC structure

/**
 * Individual file entry in the manifest
 */
export interface ManifestFile {
  path: string;           // Relative path within app
  origin: FileOrigin;
  checksum: string;       // SHA-256 hash of content
  generatedChecksum?: string;  // Original checksum if generated (to detect modifications)
  description?: string;   // Human-readable description
}

/**
 * Build manifest stored in .uccbuild/manifest.json
 */
export interface UCCBuildManifest {
  version: '1.0.0';
  appId: string;
  displayName: string;
  appVersion: string;
  createdAt: string;
  updatedAt: string;

  // The source globalConfig that drives generation
  globalConfigPath: string;

  // All tracked files
  files: ManifestFile[];

  // Build metadata
  build: {
    uccFrameworkVersion?: string;
    builderVersion: string;
    lastBuildAt?: string;
  };
}

/**
 * Result of analyzing an imported app
 */
export interface ImportAnalysis {
  appId: string;
  displayName: string;
  version: string;
  author?: string;
  email?: string;
  globalConfig: object | null;
  files: Array<{
    path: string;
    origin: FileOrigin;
    content: string;
    checksum: string;
  }>;
  warnings: string[];
  isUCCApp: boolean;
}



/**
 * Portable project file format (.uccproject)
 */
export interface UCCProjectFile {
  version: '1.0.0';
  metadata: {
    name: string;
    displayName: string;
    description: string;
    author: string;
    version: string;
    appId: string;
  };
  branding: {
    navBarColor: string;
    logoPath?: string;
  };
  globalConfig: object;
  customFiles: string[];  // Paths to custom files to include
}

/**
 * Patterns for identifying file origins
 */
export const FILE_PATTERNS = {
  // Files that are always considered source
  source: [
    'globalConfig.json',
    'package/globalConfig.json',
    'app.manifest',
    'package/app.manifest',
  ],

  // Files generated by ucc-gen (can be regenerated)
  generated: [
    /^[^/]+\/default\/app\.conf$/,
    // Only the specific nav and views files UCC creates
    /^[^/]+\/default\/data\/ui\/nav\/default\.xml$/,
    /^[^/]+\/default\/data\/ui\/views\/(configuration|dashboard|inputs)\.xml$/,
    /^[^/]+\/README\/.*$/,
    /^[^/]+\/static\/appIcon.*$/,
    // lib/* is UCC-generated except requirements.txt
    /^[^/]+\/lib\/(?!requirements\.txt$).+$/,
    /^[^/]+\/bin\/[^/]+\.py$/,  // Generated input handlers
    /^[^/]+\/default\/restmap\.conf$/,
    /^[^/]+\/default\/web\.conf$/,
    // appserver artefacts are all UCC-built
    /^[^/]+\/appserver\/static\/js\/.*$/,
    /^[^/]+\/appserver\/static\/openapi\.json$/,
    /^[^/]+\/appserver\/templates\/.*$/,
    // Other UCC-generated files (may be modified — fingerprint comparison detects this)
    /^[^/]+\/README\.txt$/,
    /^[^/]+\/VERSION$/,
    /^[^/]+\/default\/[^/]+_settings\.conf$/,  // e.g. myapp_settings.conf
    /^[^/]+\/default\/inputs\.conf$/,
    /^[^/]+\/default\/server\.conf$/,
  ],

  // Directories that contain user source code
  sourceDirectories: [
    'package/bin/',
    'package/default/',
    'package/lib/',
  ],
} as const;
